apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: celery
          image: ekeneo1/microservice-celery:latest
          command: ["celery", "-A", "microservice", "worker", "-l", "info"]
          envFrom:
            - secretRef:
                name: microservice-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
