apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432       # Port exposed inside the cluster
      targetPort: 5432 # Port exposed by the Postgres container
